Add new queue manager

diff --git a/debian/clearwater-queue-manager.prerm b/debian/clearwater-queue-manager.prerm
--- a/debian/clearwater-queue-manager.prerm
+++ b/debian/clearwater-queue-manager.prerm
@@ -1,3 +1,5 @@
+#!/bin/sh
+
 # Project Clearwater - IMS in the Cloud
 # Copyright (C) 2015  Metaswitch Networks Ltd
 #
@@ -30,41 +32,57 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
-from metaswitch.clearwater.config_manager.plugin_base import ConfigPluginBase, FileStatus
-from metaswitch.clearwater.etcd_shared.plugin_utils import run_command, safely_write
-from time import sleep
-import logging
-import shutil
-import os
+#
+# see: dh_installdeb(1)
 
-_log = logging.getLogger("shared_config_plugin")
-_file = "/etc/clearwater/shared_config"
+set -e
 
-class SharedConfigPlugin(ConfigPluginBase):
-    def __init__(self, _params):
-        pass
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-    def key(self):
-        return "shared_config"
+NAME=clearwater-queue-manager
+BASE_DIR=/usr/share/clearwater/clearwater-queue-manager
 
-    def file(self):
-        return _file
+case "$1" in
+    remove|upgrade|deconfigure)
+        # Stop monitoring the process
+        rm -f /etc/monit/conf.d/clearwater-queue-manager.monit
+        reload clearwater-monit &> /dev/null || true
+        # Make sure the process is stopped - do this before env is removed,
+        # or init.d script won't work
+        service clearwater-queue-manager stop
+        # Now do necessary cleanup
+        rm -rf $BASE_DIR/env
+        rm -rf /var/run/$NAME
 
-    def status(self, value):
-        try:
-            with open(_file, "r") as ifile:
-                current = ifile.read()
-                if current == value:
-                    return FileStatus.UP_TO_DATE
-                else:
-                    return FileStatus.OUT_OF_SYNC
-        except IOError:
-            return FileStatus.MISSING
+        # Don't remove the user if we're just upgrading.
+        if [ $1 != "upgrade" ]; then
+          if grep -q "^$NAME:" /etc/passwd ; then
+            userdel $NAME
+          fi
+        fi
+    ;;
 
-    def on_config_changed(self, value, alarm):
-        _log.info("Updating shared configuration file")
-        safely_write(_file, value)
-        run_command("/usr/share/clearwater/clearwater-queue-manager/scripts/modify_nodes_in_queue add apply_config")
+    failed-upgrade)
+    ;;
 
-def load_as_plugin(params):
-    return SharedConfigPlugin(params)
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
