Backup / Restore Markups
Remvoe is_config_synchronized and add return codes to is_config_synchronized
instead

Correctly don't include apply_config.

diff --git a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/backup_config b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/backup_config
--- a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/backup_config
+++ b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/backup_config
@@ -57,17 +57,18 @@ if [ $rc != 0 ] ; then
 fi
 
 
-while read -r key; do
+while read -r full_key; do
+  key=${full_key/$top_key/}
   if [ "$key" != "apply_config" ]; then
-    backup_file=${backup_directory}/${key/$top_key/}
+    backup_file=${backup_directory}/$key
 
-    clearwater-etcdctl get $key > "${backup_file}" 2> /tmp/backup_config.$key.$$
+    clearwater-etcdctl get $full_key > "${backup_file}" 2> /tmp/backup_config.$key.$$
 
     rc=$?
 
     # Check the return code and log if appropriate.
     if [ $rc != 0 ] ; then
-      echo "Failed to get $key from etcd config with return code $rc" >&2
+      echo "Failed to get $full_key from etcd config with return code $rc" >&2
       cat /tmp/backup_config.$key.$$              >&2
       exit 3
     fi
diff --git a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync
--- a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync
+++ b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync
@@ -31,13 +31,21 @@
 # "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
+
+# Exit codes:
+# 0     - Config is synchronized
+# 1     - Config is not synchronized
+# 2     - Run without root permissions
+# Other - An error occurred
+
 if [[ $EUID -ne 0 ]]
 then
   echo "You must run this script with root permissions"
-  exit 1
+  exit 2
 fi
 
 local_site_name=site1
 etcd_key=clearwater
 . /etc/clearwater/config
 /usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync.py "${management_local_ip:-$local_ip}" "$local_site_name" "$etcd_key"
+exit $?
diff --git a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/restore_config b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/restore_config
--- a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/restore_config
+++ b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/restore_config
@@ -68,16 +68,17 @@ FILES="${backup_directory}/*"
 
 for f in $FILES
 do
-  if [ $(basename $f) != "apply_config" ]; then
+  key=$(basename $f)
+  if [ $key != "apply_config" ]; then
     # Upload the file to etcd
-    keypath=http://${management_local_ip:-$local_ip}:4000/v2/keys/${top_key}/$(basename $f)
-    tmp_file=/tmp/restore-config.$(basename $f)
+    keypath=http://${management_local_ip:-$local_ip}:4000/v2/keys/${top_key}/$key
+    tmp_file=/tmp/restore-config.$key
     curl -X PUT $keypath --data-urlencode value@${f} 2> ${tmp_file}.stderr.$$ | tee ${tmp_file}.stdout.$$ | egrep -q "\"action\":\"set\""
     rc=$?
 
     # Check the return code and log if appropriate.
     if [ $rc != 0 ] ; then
-      echo "Failed to upload $f to etcd with return code $rc" >&2
+      echo "Failed to upload key $key to etcd with return code $rc" >&2
       cat ${tmp_file}.stderr.$$              >&2
       cat ${tmp_file}.stdout.$$              >&2
       exit 3
