bash script prints error message and exit if validation fails

diff --git a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_dns_json b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_dns_json
--- a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_dns_json
+++ b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_dns_json
@@ -19,6 +19,13 @@ SCHEMA=/usr/share/clearwater/clearwater-config-manager/scripts/config_validation
 # Validate config json against schema for syntactic errors
 python /usr/share/clearwater/clearwater-config-manager/scripts/validate_config.py $SCHEMA $FILENAME 
 
+# Abort uploading and warn user if validation fails
+rc=$?
+if [[ $rc != 0 ]]; then
+  echo "Abort uploading $FILENAME, pls fix syntax and upload again"
+  return $rc
+fi
+
 # Check we can contact `etcd`
 if ! nc -z ${management_local_ip:-$local_ip} 4000
 then
