Call validation checking scripts before uploading shared config

diff --git a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
--- a/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
+++ b/clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
@@ -69,6 +69,43 @@ then
   exit 2
 fi
 
+# Run any config validation scripts (either native or supplied by an integrator)
+any_scripts=$(ls /usr/share/clearwater/clearwater-config-manager/scripts/config_validation/* 2> /dev/null)
+if [ "$any_scripts" != "" ]
+then
+  echo "Validating /etc/clearwater/shared_config"
+  ignored_error=false
+  for script in /usr/share/clearwater/clearwater-config-manager/scripts/config_validation/*
+  do
+    if [ -x "$script" ]
+    then
+      # Script is executable.  Run it
+      "$script"
+      rc=$?
+
+      # Check the return code and abort if appropriate.
+      if [ $rc != 0 ]
+      then
+        # Abort unless forcing
+        if $force
+        then
+          ignored_error=true
+        else
+          echo "Validation of /etc/clearwater/shared_config failed - aborting upload"
+          exit $rc
+        fi
+      fi
+    fi
+  done
+
+  if $ignored_error
+  then
+    echo "Validation of /etc/clearwater/shared_config failed - continuing upload"
+  else
+    echo "Validation of /etc/clearwater/shared_config succeeded"
+  fi
+fi
+
 # Fill out audit log with changes to shared_config
 keypath=http://${management_local_ip:-$local_ip}:4000/v2/keys/$etcd_key/$local_site_name/configuration/shared_config
 python /usr/share/clearwater/clearwater-config-manager/scripts/log_shared_config.py $keypath
